name: modl-bridge
main: gg.modl.bridge.ModlBridgePlugin
version: '1.0.1'
author: tigerbong, byteful
description: Bridges spigot-only features to the modl plugin.
api-version: '1.13'
softdepend: [GrimAC, Polar, modl]
commands:
  proxycmd:
    description: Console-only command forwarder to the modl proxy plugin via TCP query
    usage: /<command> <command-to-forward>
